---
steps:
  - name: ":docker:"
    command: "bin/buildkite bin/ci build"
    agents:
      queue: native
      docker: builder

  - type: "waiter"

  - name: ":pill:"
    command: "bin/buildkite bin/ci run bin/test"
    agents:
      queue: elastic

  - type: "waiter"

  - name: ":buildkite:"
    command: "bin/buildkite bin/ci initiate-deploy staging"
    branches: "master release/*"
    agents:
      queue: elastic
